name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    # Build and cache conda environment
    # Run unit tests using pytest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
          # - os: macos-latest
          #   label: osx-64
          #   prefix: /Users/runner/miniconda3/envs/robotools
          # - os: windows-latest
          #   label: win-64
          #   prefix: C:\Miniconda3\envs\robotools

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Package Development Environment
        shell: bash -l {0}
        run: |
          pip install -e '.[dev]'

      - name: Run tests
        shell: bash -l {0}
        run: pytest --cov --cov-report xml

      - name: Upload Coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: ./coverage.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}