name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    # Build and cache conda environment
    # Run unit tests using pytest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/serial-protocol-env-py
          # - os: macos-latest
          #   label: osx-64
          #   prefix: /Users/runner/miniconda3/envs/robotools
          # - os: windows-latest
          #   label: win-64
          #   prefix: C:\Miniconda3\envs\robotools

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            activate-environment: serial-protocol-env-py
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n serial-protocol-env-py -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install Serial Protocol - Python
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: pytest --cov --cov-report xml

      - name: Upload Coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: ./coverage.xml
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}