name: documentation

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write  # This allows GitHub Actions to push to the repo

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Package Development Environment
        shell: bash -l {0}
        run: |
          pip install -e '.[dev]'

      - name: Generate Documentation
        shell: bash -l {0}
        run: cd docs && make html

      # Create an artifact of the html output.
      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/build/html/

      # Publish built docs to gh-pages branch
      - name: Commit documentation changes
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jmount1992/serial_protocol_python.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          git push origin gh-pages
